spring.application.name=kitchen-service

server.port=8082

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/kitchen_db}
spring.datasource.username=${DB_USERNAME:prabhu}
spring.datasource.password=${DB_PASSWORD:prabhu25}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
