spring.application.name=camunda-service
server.port=8084

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/camunda_db}
spring.datasource.username=${DB_USERNAME:prabhu}
spring.datasource.password=${DB_PASSWORD:prabhu25}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

camunda.bpm.admin-user.id=admin
camunda.bpm.admin-user.password=admin
camunda.bpm.admin-user.firstName=Admin

# Add this at the bottom
camunda.bpm.generic-properties.properties.skipIsolationLevelCheck=true

# ActiveMQ Configuration
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin